on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Example of curl
    steps:
    - uses: actions/checkout@v2
    - id: geth
      uses: ./
    - name: curl
      run: |
        curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' http://localhost:8501 -H "Content-Type: application/json"
      shell: bash
